export interface WordEntry {
  palavra: string;
  categoria: string;
  dificuldade: "F" | "M" | "D";
}

export const WORD_BANK: WordEntry[] = [
  // 1. Casa e Objetos Domésticos
  { palavra: "Casa", categoria: "Casa e Objetos Domésticos", dificuldade: "F" },
  { palavra: "Porta", categoria: "Casa e Objetos Domésticos", dificuldade: "F" },
  { palavra: "Mesa", categoria: "Casa e Objetos Domésticos", dificuldade: "F" },
  { palavra: "Cama", categoria: "Casa e Objetos Domésticos", dificuldade: "F" },
  { palavra: "Chave", categoria: "Casa e Objetos Domésticos", dificuldade: "F" },
  { palavra: "Espelho", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Relógio", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Cortina", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Tapete", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Lâmpada", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Travesseiro", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },
  { palavra: "Cobertor", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },
  { palavra: "Varal", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Vassoura", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },
  { palavra: "Escova", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Toalha", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Almofada", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },
  { palavra: "Armário", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },
  { palavra: "Cadeira", categoria: "Casa e Objetos Domésticos", dificuldade: "M" },
  { palavra: "Poltrona", categoria: "Casa e Objetos Domésticos", dificuldade: "D" },

  // 2. Alimentos e Bebidas
  { palavra: "Pão", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Café", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Leite", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Arroz", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Feijão", categoria: "Alimentos e Bebidas", dificuldade: "M" },
  { palavra: "Queijo", categoria: "Alimentos e Bebidas", dificuldade: "M" },
  { palavra: "Manteiga", categoria: "Alimentos e Bebidas", dificuldade: "D" },
  { palavra: "Laranja", categoria: "Alimentos e Bebidas", dificuldade: "M" },
  { palavra: "Banana", categoria: "Alimentos e Bebidas", dificuldade: "M" },
  { palavra: "Melancia", categoria: "Alimentos e Bebidas", dificuldade: "D" },
  { palavra: "Chocolate", categoria: "Alimentos e Bebidas", dificuldade: "D" },
  { palavra: "Biscoito", categoria: "Alimentos e Bebidas", dificuldade: "D" },
  { palavra: "Mel", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Farinha", categoria: "Alimentos e Bebidas", dificuldade: "D" },
  { palavra: "Ovo", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Peixe", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Carne", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Sopa", categoria: "Alimentos e Bebidas", dificuldade: "F" },
  { palavra: "Salada", categoria: "Alimentos e Bebidas", dificuldade: "M" },
  { palavra: "Pipoca", categoria: "Alimentos e Bebidas", dificuldade: "M" },

  // 3. Animais
  { palavra: "Cão", categoria: "Animais", dificuldade: "F" },
  { palavra: "Gato", categoria: "Animais", dificuldade: "F" },
  { palavra: "Peixe", categoria: "Animais", dificuldade: "F" },
  { palavra: "Pássaro", categoria: "Animais", dificuldade: "M" },
  { palavra: "Tartaruga", categoria: "Animais", dificuldade: "D" },
  { palavra: "Elefante", categoria: "Animais", dificuldade: "D" },
  { palavra: "Borboleta", categoria: "Animais", dificuldade: "D" },
  { palavra: "Formiga", categoria: "Animais", dificuldade: "M" },
  { palavra: "Abelha", categoria: "Animais", dificuldade: "M" },
  { palavra: "Coelho", categoria: "Animais", dificuldade: "M" },
  { palavra: "Cavalo", categoria: "Animais", dificuldade: "M" },
  { palavra: "Vaca", categoria: "Animais", dificuldade: "F" },
  { palavra: "Galinha", categoria: "Animais", dificuldade: "M" },
  { palavra: "Sapo", categoria: "Animais", dificuldade: "F" },
  { palavra: "Cobra", categoria: "Animais", dificuldade: "M" },
  { palavra: "Aranha", categoria: "Animais", dificuldade: "M" },
  { palavra: "Leão", categoria: "Animais", dificuldade: "F" },
  { palavra: "Urso", categoria: "Animais", dificuldade: "F" },
  { palavra: "Macaco", categoria: "Animais", dificuldade: "M" },
  { palavra: "Girafa", categoria: "Animais", dificuldade: "M" },

  // 4. Natureza e Paisagem
  { palavra: "Rio", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Mar", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Praia", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Montanha", categoria: "Natureza e Paisagem", dificuldade: "D" },
  { palavra: "Floresta", categoria: "Natureza e Paisagem", dificuldade: "D" },
  { palavra: "Deserto", categoria: "Natureza e Paisagem", dificuldade: "D" },
  { palavra: "Cachoeira", categoria: "Natureza e Paisagem", dificuldade: "D" },
  { palavra: "Vulcão", categoria: "Natureza e Paisagem", dificuldade: "M" },
  { palavra: "Ilha", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Lago", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Vale", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Colina", categoria: "Natureza e Paisagem", dificuldade: "M" },
  { palavra: "Caverna", categoria: "Natureza e Paisagem", dificuldade: "M" },
  { palavra: "Pedra", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Areia", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Nuvem", categoria: "Natureza e Paisagem", dificuldade: "M" },
  { palavra: "Estrela", categoria: "Natureza e Paisagem", dificuldade: "M" },
  { palavra: "Lua", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Sol", categoria: "Natureza e Paisagem", dificuldade: "F" },
  { palavra: "Trovão", categoria: "Natureza e Paisagem", dificuldade: "M" },

  // 5. Transporte
  { palavra: "Carro", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Ônibus", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Trem", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Avião", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Bicicleta", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Moto", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Barco", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Navio", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Caminhão", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Metrô", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Táxi", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Helicóptero", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Trator", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Carroça", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Skate", categoria: "Transporte", dificuldade: "F" },
  { palavra: "Patinete", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Balão", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Elevador", categoria: "Transporte", dificuldade: "D" },
  { palavra: "Escada", categoria: "Transporte", dificuldade: "M" },
  { palavra: "Ponte", categoria: "Transporte", dificuldade: "F" },

  // 6. Ferramentas e Objetos de Trabalho
  { palavra: "Martelo", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Chave", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "F" },
  { palavra: "Prego", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Parafuso", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Serra", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Machado", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Furadeira", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Alicate", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Régua", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Tesoura", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Pincel", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Corda", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Escada", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Balde", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Pá", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "F" },
  { palavra: "Enxada", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "D" },
  { palavra: "Fita", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "F" },
  { palavra: "Trena", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },
  { palavra: "Lixa", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "F" },
  { palavra: "Grampo", categoria: "Ferramentas e Objetos de Trabalho", dificuldade: "M" },

  // 7. Corpo Humano
  { palavra: "Mão", categoria: "Corpo Humano", dificuldade: "F" },
  { palavra: "Pé", categoria: "Corpo Humano", dificuldade: "F" },
  { palavra: "Olho", categoria: "Corpo Humano", dificuldade: "F" },
  { palavra: "Boca", categoria: "Corpo Humano", dificuldade: "F" },
  { palavra: "Nariz", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Orelha", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Cabelo", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Braço", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Perna", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Dedo", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Joelho", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Ombro", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Coração", categoria: "Corpo Humano", dificuldade: "D" },
  { palavra: "Pulmão", categoria: "Corpo Humano", dificuldade: "D" },
  { palavra: "Cérebro", categoria: "Corpo Humano", dificuldade: "D" },
  { palavra: "Dente", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Unha", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Testa", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Queixo", categoria: "Corpo Humano", dificuldade: "M" },
  { palavra: "Cotovelo", categoria: "Corpo Humano", dificuldade: "D" },

  // 8. Vestuário e Acessórios
  { palavra: "Sapato", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Camisa", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Calça", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Vestido", categoria: "Vestuário e Acessórios", dificuldade: "D" },
  { palavra: "Chapéu", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Óculos", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Relógio", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Cinto", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Meia", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Luva", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Bolsa", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Casaco", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Blusa", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Boné", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Anel", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Colar", categoria: "Vestuário e Acessórios", dificuldade: "F" },
  { palavra: "Brinco", categoria: "Vestuário e Acessórios", dificuldade: "M" },
  { palavra: "Cachecol", categoria: "Vestuário e Acessórios", dificuldade: "D" },
  { palavra: "Sandália", categoria: "Vestuário e Acessórios", dificuldade: "D" },
  { palavra: "Gravata", categoria: "Vestuário e Acessórios", dificuldade: "D" },

  // 9. Instrumentos Musicais
  { palavra: "Violão", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Piano", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Tambor", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Flauta", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Violino", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Guitarra", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Bateria", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Trompete", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Harpa", categoria: "Instrumentos Musicais", dificuldade: "F" },
  { palavra: "Sino", categoria: "Instrumentos Musicais", dificuldade: "F" },
  { palavra: "Pandeiro", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Gaita", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Tuba", categoria: "Instrumentos Musicais", dificuldade: "F" },
  { palavra: "Saxofone", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Xilofone", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Berimbau", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Cavaquinho", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Maracá", categoria: "Instrumentos Musicais", dificuldade: "M" },
  { palavra: "Chocalho", categoria: "Instrumentos Musicais", dificuldade: "D" },
  { palavra: "Acordeão", categoria: "Instrumentos Musicais", dificuldade: "D" },

  // 10. Papelaria e Escritório
  { palavra: "Lápis", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Caneta", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Papel", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Borracha", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Caderno", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Régua", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Tesoura", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Cola", categoria: "Papelaria e Escritório", dificuldade: "F" },
  { palavra: "Grampeador", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Envelope", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Clipe", categoria: "Papelaria e Escritório", dificuldade: "F" },
  { palavra: "Marcador", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Pasta", categoria: "Papelaria e Escritório", dificuldade: "F" },
  { palavra: "Calculadora", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Agenda", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Etiqueta", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Apontador", categoria: "Papelaria e Escritório", dificuldade: "D" },
  { palavra: "Carimbo", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Pincel", categoria: "Papelaria e Escritório", dificuldade: "M" },
  { palavra: "Estojo", categoria: "Papelaria e Escritório", dificuldade: "M" },

  // 11. Esporte e Lazer
  { palavra: "Bola", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Rede", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Raquete", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Piscina", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Bicicleta", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Skate", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Pipa", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Boneca", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Quebra-cabeça", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Dado", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Carta", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Corda", categoria: "Esporte e Lazer", dificuldade: "M" },
  { palavra: "Patins", categoria: "Esporte e Lazer", dificuldade: "M" },
  { palavra: "Arco", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Alvo", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Luva", categoria: "Esporte e Lazer", dificuldade: "F" },
  { palavra: "Capacete", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Chuteira", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Tabuleiro", categoria: "Esporte e Lazer", dificuldade: "D" },
  { palavra: "Bola de gude", categoria: "Esporte e Lazer", dificuldade: "D" },

  // 12. Elementos Climáticos e Astronômicos
  { palavra: "Chuva", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Vento", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Neve", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Gelo", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Trovão", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Raio", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Arco-íris", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "D" },
  { palavra: "Nevoeiro", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "D" },
  { palavra: "Geada", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Tempestade", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "D" },
  { palavra: "Estrela", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Lua", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Sol", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Planeta", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "D" },
  { palavra: "Cometa", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Nuvem", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Céu", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "F" },
  { palavra: "Orvalho", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "D" },
  { palavra: "Bruma", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },
  { palavra: "Aurora", categoria: "Elementos Climáticos e Astronômicos", dificuldade: "M" },

  // 13. Lugares e Construções
  { palavra: "Escola", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Igreja", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Ponte", categoria: "Lugares e Construções", dificuldade: "F" },
  { palavra: "Castelo", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Torre", categoria: "Lugares e Construções", dificuldade: "F" },
  { palavra: "Praça", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Mercado", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Farol", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Estação", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Fazenda", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Cidade", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Vila", categoria: "Lugares e Construções", dificuldade: "F" },
  { palavra: "Muro", categoria: "Lugares e Construções", dificuldade: "F" },
  { palavra: "Portão", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Telhado", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Jardim", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Quintal", categoria: "Lugares e Construções", dificuldade: "M" },
  { palavra: "Varanda", categoria: "Lugares e Construções", dificuldade: "D" },
  { palavra: "Cerca", categoria: "Lugares e Construções", dificuldade: "F" },
  { palavra: "Poço", categoria: "Lugares e Construções", dificuldade: "F" },

  // 14. Utensílios de Cozinha
  { palavra: "Panela", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Faca", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Garfo", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Colher", categoria: "Utensílios de Cozinha", dificuldade: "M" },
  { palavra: "Prato", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Copo", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Xícara", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Frigideira", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Tábua", categoria: "Utensílios de Cozinha", dificuldade: "M" },
  { palavra: "Peneira", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Liquidificador", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Forno", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Fogão", categoria: "Utensílios de Cozinha", dificuldade: "M" },
  { palavra: "Geladeira", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Bandeja", categoria: "Utensílios de Cozinha", dificuldade: "M" },
  { palavra: "Escumadeira", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Ralador", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Jarra", categoria: "Utensílios de Cozinha", dificuldade: "F" },
  { palavra: "Panela de pressão", categoria: "Utensílios de Cozinha", dificuldade: "D" },
  { palavra: "Abridor", categoria: "Utensílios de Cozinha", dificuldade: "D" },

  // 15. Plantas e Flores
  { palavra: "Rosa", categoria: "Plantas e Flores", dificuldade: "F" },
  { palavra: "Girassol", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Margarida", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Cacto", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Árvore", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Folha", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Raiz", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Semente", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Grama", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Musgo", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Orquídea", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Tulipa", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Samambaia", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Bambu", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Trepadeira", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Videira", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Palmeira", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Pinheiro", categoria: "Plantas e Flores", dificuldade: "D" },
  { palavra: "Lírio", categoria: "Plantas e Flores", dificuldade: "M" },
  { palavra: "Violeta", categoria: "Plantas e Flores", dificuldade: "M" },

  // 16. Objetos Diversos
  { palavra: "Chave", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Moeda", categoria: "Objetos Diversos", dificuldade: "M" },
  { palavra: "Relógio", categoria: "Objetos Diversos", dificuldade: "M" },
  { palavra: "Espelho", categoria: "Objetos Diversos", dificuldade: "M" },
  { palavra: "Vela", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Sino", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Cofre", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Lanterna", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Baú", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Malote", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Envelope", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Retrato", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Boneco", categoria: "Objetos Diversos", dificuldade: "M" },
  { palavra: "Ímã", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Corrente", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Fivela", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Lupa", categoria: "Objetos Diversos", dificuldade: "F" },
  { palavra: "Isqueiro", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Termômetro", categoria: "Objetos Diversos", dificuldade: "D" },
  { palavra: "Bússola", categoria: "Objetos Diversos", dificuldade: "D" },
];

export const CATEGORIES = [
  "Casa e Objetos Domésticos",
  "Alimentos e Bebidas",
  "Animais",
  "Natureza e Paisagem",
  "Transporte",
  "Ferramentas e Objetos de Trabalho",
  "Corpo Humano",
  "Vestuário e Acessórios",
  "Instrumentos Musicais",
  "Papelaria e Escritório",
  "Esporte e Lazer",
  "Elementos Climáticos e Astronômicos",
  "Lugares e Construções",
  "Utensílios de Cozinha",
  "Plantas e Flores",
  "Objetos Diversos",
] as const;
