/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StroopRouteImport } from './routes/stroop'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SlideRouteImport } from './routes/slide'
import { Route as SequenciaRouteImport } from './routes/sequencia'
import { Route as RegraRouteImport } from './routes/regra'
import { Route as RecallRouteImport } from './routes/recall'
import { Route as MorseRouteImport } from './routes/morse'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as MatrizRouteImport } from './routes/matriz'
import { Route as GridRouteImport } from './routes/grid'
import { Route as EinsteinRouteImport } from './routes/einstein'
import { Route as DicoticoRouteImport } from './routes/dicotico'
import { Route as CruzadaRouteImport } from './routes/cruzada'
import { Route as CriptoRouteImport } from './routes/cripto'
import { Route as CofresRouteImport } from './routes/cofres'
import { Route as CalculoRouteImport } from './routes/calculo'
import { Route as AritRouteImport } from './routes/arit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StroopIndexRouteImport } from './routes/stroop.index'
import { Route as SlideIndexRouteImport } from './routes/slide.index'
import { Route as SequenciaIndexRouteImport } from './routes/sequencia.index'
import { Route as RegraIndexRouteImport } from './routes/regra.index'
import { Route as RecallIndexRouteImport } from './routes/recall.index'
import { Route as MorseIndexRouteImport } from './routes/morse.index'
import { Route as MemoriaIndexRouteImport } from './routes/memoria.index'
import { Route as MatrizIndexRouteImport } from './routes/matriz.index'
import { Route as GridIndexRouteImport } from './routes/grid.index'
import { Route as EinsteinIndexRouteImport } from './routes/einstein.index'
import { Route as DicoticoIndexRouteImport } from './routes/dicotico.index'
import { Route as CruzadaIndexRouteImport } from './routes/cruzada.index'
import { Route as CriptoIndexRouteImport } from './routes/cripto.index'
import { Route as CofresIndexRouteImport } from './routes/cofres.index'
import { Route as CalculoIndexRouteImport } from './routes/calculo.index'
import { Route as AritIndexRouteImport } from './routes/arit.index'
import { Route as StroopJogarRouteImport } from './routes/stroop.jogar'
import { Route as SlideJogarRouteImport } from './routes/slide.jogar'
import { Route as SequenciaJogarRouteImport } from './routes/sequencia.jogar'
import { Route as RegraJogarRouteImport } from './routes/regra.jogar'
import { Route as RecallResultadoRouteImport } from './routes/recall.resultado'
import { Route as RecallJogarRouteImport } from './routes/recall.jogar'
import { Route as MorseMundo1RouteImport } from './routes/morse.mundo-1'
import { Route as MemoriaResultadoRouteImport } from './routes/memoria.resultado'
import { Route as MemoriaJogarRouteImport } from './routes/memoria.jogar'
import { Route as MatrizJogarRouteImport } from './routes/matriz.jogar'
import { Route as GridJogarRouteImport } from './routes/grid.jogar'
import { Route as EinsteinJogarRouteImport } from './routes/einstein.jogar'
import { Route as DicoticoJogarRouteImport } from './routes/dicotico.jogar'
import { Route as CruzadaJogarRouteImport } from './routes/cruzada.jogar'
import { Route as CriptoJogarRouteImport } from './routes/cripto.jogar'
import { Route as CofresJogarRouteImport } from './routes/cofres.jogar'
import { Route as CalculoResultadoRouteImport } from './routes/calculo.resultado'
import { Route as CalculoJogarRouteImport } from './routes/calculo.jogar'
import { Route as AritJogarRouteImport } from './routes/arit.jogar'

const StroopRoute = StroopRouteImport.update({
  id: '/stroop',
  path: '/stroop',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideRoute = SlideRouteImport.update({
  id: '/slide',
  path: '/slide',
  getParentRoute: () => rootRouteImport,
} as any)
const SequenciaRoute = SequenciaRouteImport.update({
  id: '/sequencia',
  path: '/sequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RegraRoute = RegraRouteImport.update({
  id: '/regra',
  path: '/regra',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallRoute = RecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const MorseRoute = MorseRouteImport.update({
  id: '/morse',
  path: '/morse',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizRoute = MatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsteinRoute = EinsteinRouteImport.update({
  id: '/einstein',
  path: '/einstein',
  getParentRoute: () => rootRouteImport,
} as any)
const DicoticoRoute = DicoticoRouteImport.update({
  id: '/dicotico',
  path: '/dicotico',
  getParentRoute: () => rootRouteImport,
} as any)
const CruzadaRoute = CruzadaRouteImport.update({
  id: '/cruzada',
  path: '/cruzada',
  getParentRoute: () => rootRouteImport,
} as any)
const CriptoRoute = CriptoRouteImport.update({
  id: '/cripto',
  path: '/cripto',
  getParentRoute: () => rootRouteImport,
} as any)
const CofresRoute = CofresRouteImport.update({
  id: '/cofres',
  path: '/cofres',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculoRoute = CalculoRouteImport.update({
  id: '/calculo',
  path: '/calculo',
  getParentRoute: () => rootRouteImport,
} as any)
const AritRoute = AritRouteImport.update({
  id: '/arit',
  path: '/arit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StroopIndexRoute = StroopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StroopRoute,
} as any)
const SlideIndexRoute = SlideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlideRoute,
} as any)
const SequenciaIndexRoute = SequenciaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SequenciaRoute,
} as any)
const RegraIndexRoute = RegraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegraRoute,
} as any)
const RecallIndexRoute = RecallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecallRoute,
} as any)
const MorseIndexRoute = MorseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MorseRoute,
} as any)
const MemoriaIndexRoute = MemoriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriaRoute,
} as any)
const MatrizIndexRoute = MatrizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatrizRoute,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GridRoute,
} as any)
const EinsteinIndexRoute = EinsteinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EinsteinRoute,
} as any)
const DicoticoIndexRoute = DicoticoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DicoticoRoute,
} as any)
const CruzadaIndexRoute = CruzadaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CruzadaRoute,
} as any)
const CriptoIndexRoute = CriptoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CriptoRoute,
} as any)
const CofresIndexRoute = CofresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CofresRoute,
} as any)
const CalculoIndexRoute = CalculoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalculoRoute,
} as any)
const AritIndexRoute = AritIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AritRoute,
} as any)
const StroopJogarRoute = StroopJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => StroopRoute,
} as any)
const SlideJogarRoute = SlideJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => SlideRoute,
} as any)
const SequenciaJogarRoute = SequenciaJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => SequenciaRoute,
} as any)
const RegraJogarRoute = RegraJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => RegraRoute,
} as any)
const RecallResultadoRoute = RecallResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => RecallRoute,
} as any)
const RecallJogarRoute = RecallJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => RecallRoute,
} as any)
const MorseMundo1Route = MorseMundo1RouteImport.update({
  id: '/mundo-1',
  path: '/mundo-1',
  getParentRoute: () => MorseRoute,
} as any)
const MemoriaResultadoRoute = MemoriaResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => MemoriaRoute,
} as any)
const MemoriaJogarRoute = MemoriaJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => MemoriaRoute,
} as any)
const MatrizJogarRoute = MatrizJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => MatrizRoute,
} as any)
const GridJogarRoute = GridJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => GridRoute,
} as any)
const EinsteinJogarRoute = EinsteinJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => EinsteinRoute,
} as any)
const DicoticoJogarRoute = DicoticoJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => DicoticoRoute,
} as any)
const CruzadaJogarRoute = CruzadaJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CruzadaRoute,
} as any)
const CriptoJogarRoute = CriptoJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CriptoRoute,
} as any)
const CofresJogarRoute = CofresJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CofresRoute,
} as any)
const CalculoResultadoRoute = CalculoResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => CalculoRoute,
} as any)
const CalculoJogarRoute = CalculoJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CalculoRoute,
} as any)
const AritJogarRoute = AritJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => AritRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arit': typeof AritRouteWithChildren
  '/calculo': typeof CalculoRouteWithChildren
  '/cofres': typeof CofresRouteWithChildren
  '/cripto': typeof CriptoRouteWithChildren
  '/cruzada': typeof CruzadaRouteWithChildren
  '/dicotico': typeof DicoticoRouteWithChildren
  '/einstein': typeof EinsteinRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/matriz': typeof MatrizRouteWithChildren
  '/memoria': typeof MemoriaRouteWithChildren
  '/morse': typeof MorseRouteWithChildren
  '/recall': typeof RecallRouteWithChildren
  '/regra': typeof RegraRouteWithChildren
  '/sequencia': typeof SequenciaRouteWithChildren
  '/slide': typeof SlideRouteWithChildren
  '/sobre': typeof SobreRoute
  '/stroop': typeof StroopRouteWithChildren
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cofres/jogar': typeof CofresJogarRoute
  '/cripto/jogar': typeof CriptoJogarRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/dicotico/jogar': typeof DicoticoJogarRoute
  '/einstein/jogar': typeof EinsteinJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/matriz/jogar': typeof MatrizJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/morse/mundo-1': typeof MorseMundo1Route
  '/recall/jogar': typeof RecallJogarRoute
  '/recall/resultado': typeof RecallResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/sequencia/jogar': typeof SequenciaJogarRoute
  '/slide/jogar': typeof SlideJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit/': typeof AritIndexRoute
  '/calculo/': typeof CalculoIndexRoute
  '/cofres/': typeof CofresIndexRoute
  '/cripto/': typeof CriptoIndexRoute
  '/cruzada/': typeof CruzadaIndexRoute
  '/dicotico/': typeof DicoticoIndexRoute
  '/einstein/': typeof EinsteinIndexRoute
  '/grid/': typeof GridIndexRoute
  '/matriz/': typeof MatrizIndexRoute
  '/memoria/': typeof MemoriaIndexRoute
  '/morse/': typeof MorseIndexRoute
  '/recall/': typeof RecallIndexRoute
  '/regra/': typeof RegraIndexRoute
  '/sequencia/': typeof SequenciaIndexRoute
  '/slide/': typeof SlideIndexRoute
  '/stroop/': typeof StroopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cofres/jogar': typeof CofresJogarRoute
  '/cripto/jogar': typeof CriptoJogarRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/dicotico/jogar': typeof DicoticoJogarRoute
  '/einstein/jogar': typeof EinsteinJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/matriz/jogar': typeof MatrizJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/morse/mundo-1': typeof MorseMundo1Route
  '/recall/jogar': typeof RecallJogarRoute
  '/recall/resultado': typeof RecallResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/sequencia/jogar': typeof SequenciaJogarRoute
  '/slide/jogar': typeof SlideJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit': typeof AritIndexRoute
  '/calculo': typeof CalculoIndexRoute
  '/cofres': typeof CofresIndexRoute
  '/cripto': typeof CriptoIndexRoute
  '/cruzada': typeof CruzadaIndexRoute
  '/dicotico': typeof DicoticoIndexRoute
  '/einstein': typeof EinsteinIndexRoute
  '/grid': typeof GridIndexRoute
  '/matriz': typeof MatrizIndexRoute
  '/memoria': typeof MemoriaIndexRoute
  '/morse': typeof MorseIndexRoute
  '/recall': typeof RecallIndexRoute
  '/regra': typeof RegraIndexRoute
  '/sequencia': typeof SequenciaIndexRoute
  '/slide': typeof SlideIndexRoute
  '/stroop': typeof StroopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arit': typeof AritRouteWithChildren
  '/calculo': typeof CalculoRouteWithChildren
  '/cofres': typeof CofresRouteWithChildren
  '/cripto': typeof CriptoRouteWithChildren
  '/cruzada': typeof CruzadaRouteWithChildren
  '/dicotico': typeof DicoticoRouteWithChildren
  '/einstein': typeof EinsteinRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/matriz': typeof MatrizRouteWithChildren
  '/memoria': typeof MemoriaRouteWithChildren
  '/morse': typeof MorseRouteWithChildren
  '/recall': typeof RecallRouteWithChildren
  '/regra': typeof RegraRouteWithChildren
  '/sequencia': typeof SequenciaRouteWithChildren
  '/slide': typeof SlideRouteWithChildren
  '/sobre': typeof SobreRoute
  '/stroop': typeof StroopRouteWithChildren
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cofres/jogar': typeof CofresJogarRoute
  '/cripto/jogar': typeof CriptoJogarRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/dicotico/jogar': typeof DicoticoJogarRoute
  '/einstein/jogar': typeof EinsteinJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/matriz/jogar': typeof MatrizJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/morse/mundo-1': typeof MorseMundo1Route
  '/recall/jogar': typeof RecallJogarRoute
  '/recall/resultado': typeof RecallResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/sequencia/jogar': typeof SequenciaJogarRoute
  '/slide/jogar': typeof SlideJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit/': typeof AritIndexRoute
  '/calculo/': typeof CalculoIndexRoute
  '/cofres/': typeof CofresIndexRoute
  '/cripto/': typeof CriptoIndexRoute
  '/cruzada/': typeof CruzadaIndexRoute
  '/dicotico/': typeof DicoticoIndexRoute
  '/einstein/': typeof EinsteinIndexRoute
  '/grid/': typeof GridIndexRoute
  '/matriz/': typeof MatrizIndexRoute
  '/memoria/': typeof MemoriaIndexRoute
  '/morse/': typeof MorseIndexRoute
  '/recall/': typeof RecallIndexRoute
  '/regra/': typeof RegraIndexRoute
  '/sequencia/': typeof SequenciaIndexRoute
  '/slide/': typeof SlideIndexRoute
  '/stroop/': typeof StroopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arit'
    | '/calculo'
    | '/cofres'
    | '/cripto'
    | '/cruzada'
    | '/dicotico'
    | '/einstein'
    | '/grid'
    | '/matriz'
    | '/memoria'
    | '/morse'
    | '/recall'
    | '/regra'
    | '/sequencia'
    | '/slide'
    | '/sobre'
    | '/stroop'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cofres/jogar'
    | '/cripto/jogar'
    | '/cruzada/jogar'
    | '/dicotico/jogar'
    | '/einstein/jogar'
    | '/grid/jogar'
    | '/matriz/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/morse/mundo-1'
    | '/recall/jogar'
    | '/recall/resultado'
    | '/regra/jogar'
    | '/sequencia/jogar'
    | '/slide/jogar'
    | '/stroop/jogar'
    | '/arit/'
    | '/calculo/'
    | '/cofres/'
    | '/cripto/'
    | '/cruzada/'
    | '/dicotico/'
    | '/einstein/'
    | '/grid/'
    | '/matriz/'
    | '/memoria/'
    | '/morse/'
    | '/recall/'
    | '/regra/'
    | '/sequencia/'
    | '/slide/'
    | '/stroop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sobre'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cofres/jogar'
    | '/cripto/jogar'
    | '/cruzada/jogar'
    | '/dicotico/jogar'
    | '/einstein/jogar'
    | '/grid/jogar'
    | '/matriz/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/morse/mundo-1'
    | '/recall/jogar'
    | '/recall/resultado'
    | '/regra/jogar'
    | '/sequencia/jogar'
    | '/slide/jogar'
    | '/stroop/jogar'
    | '/arit'
    | '/calculo'
    | '/cofres'
    | '/cripto'
    | '/cruzada'
    | '/dicotico'
    | '/einstein'
    | '/grid'
    | '/matriz'
    | '/memoria'
    | '/morse'
    | '/recall'
    | '/regra'
    | '/sequencia'
    | '/slide'
    | '/stroop'
  id:
    | '__root__'
    | '/'
    | '/arit'
    | '/calculo'
    | '/cofres'
    | '/cripto'
    | '/cruzada'
    | '/dicotico'
    | '/einstein'
    | '/grid'
    | '/matriz'
    | '/memoria'
    | '/morse'
    | '/recall'
    | '/regra'
    | '/sequencia'
    | '/slide'
    | '/sobre'
    | '/stroop'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cofres/jogar'
    | '/cripto/jogar'
    | '/cruzada/jogar'
    | '/dicotico/jogar'
    | '/einstein/jogar'
    | '/grid/jogar'
    | '/matriz/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/morse/mundo-1'
    | '/recall/jogar'
    | '/recall/resultado'
    | '/regra/jogar'
    | '/sequencia/jogar'
    | '/slide/jogar'
    | '/stroop/jogar'
    | '/arit/'
    | '/calculo/'
    | '/cofres/'
    | '/cripto/'
    | '/cruzada/'
    | '/dicotico/'
    | '/einstein/'
    | '/grid/'
    | '/matriz/'
    | '/memoria/'
    | '/morse/'
    | '/recall/'
    | '/regra/'
    | '/sequencia/'
    | '/slide/'
    | '/stroop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AritRoute: typeof AritRouteWithChildren
  CalculoRoute: typeof CalculoRouteWithChildren
  CofresRoute: typeof CofresRouteWithChildren
  CriptoRoute: typeof CriptoRouteWithChildren
  CruzadaRoute: typeof CruzadaRouteWithChildren
  DicoticoRoute: typeof DicoticoRouteWithChildren
  EinsteinRoute: typeof EinsteinRouteWithChildren
  GridRoute: typeof GridRouteWithChildren
  MatrizRoute: typeof MatrizRouteWithChildren
  MemoriaRoute: typeof MemoriaRouteWithChildren
  MorseRoute: typeof MorseRouteWithChildren
  RecallRoute: typeof RecallRouteWithChildren
  RegraRoute: typeof RegraRouteWithChildren
  SequenciaRoute: typeof SequenciaRouteWithChildren
  SlideRoute: typeof SlideRouteWithChildren
  SobreRoute: typeof SobreRoute
  StroopRoute: typeof StroopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stroop': {
      id: '/stroop'
      path: '/stroop'
      fullPath: '/stroop'
      preLoaderRoute: typeof StroopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide': {
      id: '/slide'
      path: '/slide'
      fullPath: '/slide'
      preLoaderRoute: typeof SlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequencia': {
      id: '/sequencia'
      path: '/sequencia'
      fullPath: '/sequencia'
      preLoaderRoute: typeof SequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regra': {
      id: '/regra'
      path: '/regra'
      fullPath: '/regra'
      preLoaderRoute: typeof RegraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recall': {
      id: '/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof RecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morse': {
      id: '/morse'
      path: '/morse'
      fullPath: '/morse'
      preLoaderRoute: typeof MorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz': {
      id: '/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof MatrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstein': {
      id: '/einstein'
      path: '/einstein'
      fullPath: '/einstein'
      preLoaderRoute: typeof EinsteinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicotico': {
      id: '/dicotico'
      path: '/dicotico'
      fullPath: '/dicotico'
      preLoaderRoute: typeof DicoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruzada': {
      id: '/cruzada'
      path: '/cruzada'
      fullPath: '/cruzada'
      preLoaderRoute: typeof CruzadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cripto': {
      id: '/cripto'
      path: '/cripto'
      fullPath: '/cripto'
      preLoaderRoute: typeof CriptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofres': {
      id: '/cofres'
      path: '/cofres'
      fullPath: '/cofres'
      preLoaderRoute: typeof CofresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculo': {
      id: '/calculo'
      path: '/calculo'
      fullPath: '/calculo'
      preLoaderRoute: typeof CalculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arit': {
      id: '/arit'
      path: '/arit'
      fullPath: '/arit'
      preLoaderRoute: typeof AritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroop/': {
      id: '/stroop/'
      path: '/'
      fullPath: '/stroop/'
      preLoaderRoute: typeof StroopIndexRouteImport
      parentRoute: typeof StroopRoute
    }
    '/slide/': {
      id: '/slide/'
      path: '/'
      fullPath: '/slide/'
      preLoaderRoute: typeof SlideIndexRouteImport
      parentRoute: typeof SlideRoute
    }
    '/sequencia/': {
      id: '/sequencia/'
      path: '/'
      fullPath: '/sequencia/'
      preLoaderRoute: typeof SequenciaIndexRouteImport
      parentRoute: typeof SequenciaRoute
    }
    '/regra/': {
      id: '/regra/'
      path: '/'
      fullPath: '/regra/'
      preLoaderRoute: typeof RegraIndexRouteImport
      parentRoute: typeof RegraRoute
    }
    '/recall/': {
      id: '/recall/'
      path: '/'
      fullPath: '/recall/'
      preLoaderRoute: typeof RecallIndexRouteImport
      parentRoute: typeof RecallRoute
    }
    '/morse/': {
      id: '/morse/'
      path: '/'
      fullPath: '/morse/'
      preLoaderRoute: typeof MorseIndexRouteImport
      parentRoute: typeof MorseRoute
    }
    '/memoria/': {
      id: '/memoria/'
      path: '/'
      fullPath: '/memoria/'
      preLoaderRoute: typeof MemoriaIndexRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/matriz/': {
      id: '/matriz/'
      path: '/'
      fullPath: '/matriz/'
      preLoaderRoute: typeof MatrizIndexRouteImport
      parentRoute: typeof MatrizRoute
    }
    '/grid/': {
      id: '/grid/'
      path: '/'
      fullPath: '/grid/'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof GridRoute
    }
    '/einstein/': {
      id: '/einstein/'
      path: '/'
      fullPath: '/einstein/'
      preLoaderRoute: typeof EinsteinIndexRouteImport
      parentRoute: typeof EinsteinRoute
    }
    '/dicotico/': {
      id: '/dicotico/'
      path: '/'
      fullPath: '/dicotico/'
      preLoaderRoute: typeof DicoticoIndexRouteImport
      parentRoute: typeof DicoticoRoute
    }
    '/cruzada/': {
      id: '/cruzada/'
      path: '/'
      fullPath: '/cruzada/'
      preLoaderRoute: typeof CruzadaIndexRouteImport
      parentRoute: typeof CruzadaRoute
    }
    '/cripto/': {
      id: '/cripto/'
      path: '/'
      fullPath: '/cripto/'
      preLoaderRoute: typeof CriptoIndexRouteImport
      parentRoute: typeof CriptoRoute
    }
    '/cofres/': {
      id: '/cofres/'
      path: '/'
      fullPath: '/cofres/'
      preLoaderRoute: typeof CofresIndexRouteImport
      parentRoute: typeof CofresRoute
    }
    '/calculo/': {
      id: '/calculo/'
      path: '/'
      fullPath: '/calculo/'
      preLoaderRoute: typeof CalculoIndexRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/arit/': {
      id: '/arit/'
      path: '/'
      fullPath: '/arit/'
      preLoaderRoute: typeof AritIndexRouteImport
      parentRoute: typeof AritRoute
    }
    '/stroop/jogar': {
      id: '/stroop/jogar'
      path: '/jogar'
      fullPath: '/stroop/jogar'
      preLoaderRoute: typeof StroopJogarRouteImport
      parentRoute: typeof StroopRoute
    }
    '/slide/jogar': {
      id: '/slide/jogar'
      path: '/jogar'
      fullPath: '/slide/jogar'
      preLoaderRoute: typeof SlideJogarRouteImport
      parentRoute: typeof SlideRoute
    }
    '/sequencia/jogar': {
      id: '/sequencia/jogar'
      path: '/jogar'
      fullPath: '/sequencia/jogar'
      preLoaderRoute: typeof SequenciaJogarRouteImport
      parentRoute: typeof SequenciaRoute
    }
    '/regra/jogar': {
      id: '/regra/jogar'
      path: '/jogar'
      fullPath: '/regra/jogar'
      preLoaderRoute: typeof RegraJogarRouteImport
      parentRoute: typeof RegraRoute
    }
    '/recall/resultado': {
      id: '/recall/resultado'
      path: '/resultado'
      fullPath: '/recall/resultado'
      preLoaderRoute: typeof RecallResultadoRouteImport
      parentRoute: typeof RecallRoute
    }
    '/recall/jogar': {
      id: '/recall/jogar'
      path: '/jogar'
      fullPath: '/recall/jogar'
      preLoaderRoute: typeof RecallJogarRouteImport
      parentRoute: typeof RecallRoute
    }
    '/morse/mundo-1': {
      id: '/morse/mundo-1'
      path: '/mundo-1'
      fullPath: '/morse/mundo-1'
      preLoaderRoute: typeof MorseMundo1RouteImport
      parentRoute: typeof MorseRoute
    }
    '/memoria/resultado': {
      id: '/memoria/resultado'
      path: '/resultado'
      fullPath: '/memoria/resultado'
      preLoaderRoute: typeof MemoriaResultadoRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/memoria/jogar': {
      id: '/memoria/jogar'
      path: '/jogar'
      fullPath: '/memoria/jogar'
      preLoaderRoute: typeof MemoriaJogarRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/matriz/jogar': {
      id: '/matriz/jogar'
      path: '/jogar'
      fullPath: '/matriz/jogar'
      preLoaderRoute: typeof MatrizJogarRouteImport
      parentRoute: typeof MatrizRoute
    }
    '/grid/jogar': {
      id: '/grid/jogar'
      path: '/jogar'
      fullPath: '/grid/jogar'
      preLoaderRoute: typeof GridJogarRouteImport
      parentRoute: typeof GridRoute
    }
    '/einstein/jogar': {
      id: '/einstein/jogar'
      path: '/jogar'
      fullPath: '/einstein/jogar'
      preLoaderRoute: typeof EinsteinJogarRouteImport
      parentRoute: typeof EinsteinRoute
    }
    '/dicotico/jogar': {
      id: '/dicotico/jogar'
      path: '/jogar'
      fullPath: '/dicotico/jogar'
      preLoaderRoute: typeof DicoticoJogarRouteImport
      parentRoute: typeof DicoticoRoute
    }
    '/cruzada/jogar': {
      id: '/cruzada/jogar'
      path: '/jogar'
      fullPath: '/cruzada/jogar'
      preLoaderRoute: typeof CruzadaJogarRouteImport
      parentRoute: typeof CruzadaRoute
    }
    '/cripto/jogar': {
      id: '/cripto/jogar'
      path: '/jogar'
      fullPath: '/cripto/jogar'
      preLoaderRoute: typeof CriptoJogarRouteImport
      parentRoute: typeof CriptoRoute
    }
    '/cofres/jogar': {
      id: '/cofres/jogar'
      path: '/jogar'
      fullPath: '/cofres/jogar'
      preLoaderRoute: typeof CofresJogarRouteImport
      parentRoute: typeof CofresRoute
    }
    '/calculo/resultado': {
      id: '/calculo/resultado'
      path: '/resultado'
      fullPath: '/calculo/resultado'
      preLoaderRoute: typeof CalculoResultadoRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/calculo/jogar': {
      id: '/calculo/jogar'
      path: '/jogar'
      fullPath: '/calculo/jogar'
      preLoaderRoute: typeof CalculoJogarRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/arit/jogar': {
      id: '/arit/jogar'
      path: '/jogar'
      fullPath: '/arit/jogar'
      preLoaderRoute: typeof AritJogarRouteImport
      parentRoute: typeof AritRoute
    }
  }
}

interface AritRouteChildren {
  AritJogarRoute: typeof AritJogarRoute
  AritIndexRoute: typeof AritIndexRoute
}

const AritRouteChildren: AritRouteChildren = {
  AritJogarRoute: AritJogarRoute,
  AritIndexRoute: AritIndexRoute,
}

const AritRouteWithChildren = AritRoute._addFileChildren(AritRouteChildren)

interface CalculoRouteChildren {
  CalculoJogarRoute: typeof CalculoJogarRoute
  CalculoResultadoRoute: typeof CalculoResultadoRoute
  CalculoIndexRoute: typeof CalculoIndexRoute
}

const CalculoRouteChildren: CalculoRouteChildren = {
  CalculoJogarRoute: CalculoJogarRoute,
  CalculoResultadoRoute: CalculoResultadoRoute,
  CalculoIndexRoute: CalculoIndexRoute,
}

const CalculoRouteWithChildren =
  CalculoRoute._addFileChildren(CalculoRouteChildren)

interface CofresRouteChildren {
  CofresJogarRoute: typeof CofresJogarRoute
  CofresIndexRoute: typeof CofresIndexRoute
}

const CofresRouteChildren: CofresRouteChildren = {
  CofresJogarRoute: CofresJogarRoute,
  CofresIndexRoute: CofresIndexRoute,
}

const CofresRouteWithChildren =
  CofresRoute._addFileChildren(CofresRouteChildren)

interface CriptoRouteChildren {
  CriptoJogarRoute: typeof CriptoJogarRoute
  CriptoIndexRoute: typeof CriptoIndexRoute
}

const CriptoRouteChildren: CriptoRouteChildren = {
  CriptoJogarRoute: CriptoJogarRoute,
  CriptoIndexRoute: CriptoIndexRoute,
}

const CriptoRouteWithChildren =
  CriptoRoute._addFileChildren(CriptoRouteChildren)

interface CruzadaRouteChildren {
  CruzadaJogarRoute: typeof CruzadaJogarRoute
  CruzadaIndexRoute: typeof CruzadaIndexRoute
}

const CruzadaRouteChildren: CruzadaRouteChildren = {
  CruzadaJogarRoute: CruzadaJogarRoute,
  CruzadaIndexRoute: CruzadaIndexRoute,
}

const CruzadaRouteWithChildren =
  CruzadaRoute._addFileChildren(CruzadaRouteChildren)

interface DicoticoRouteChildren {
  DicoticoJogarRoute: typeof DicoticoJogarRoute
  DicoticoIndexRoute: typeof DicoticoIndexRoute
}

const DicoticoRouteChildren: DicoticoRouteChildren = {
  DicoticoJogarRoute: DicoticoJogarRoute,
  DicoticoIndexRoute: DicoticoIndexRoute,
}

const DicoticoRouteWithChildren = DicoticoRoute._addFileChildren(
  DicoticoRouteChildren,
)

interface EinsteinRouteChildren {
  EinsteinJogarRoute: typeof EinsteinJogarRoute
  EinsteinIndexRoute: typeof EinsteinIndexRoute
}

const EinsteinRouteChildren: EinsteinRouteChildren = {
  EinsteinJogarRoute: EinsteinJogarRoute,
  EinsteinIndexRoute: EinsteinIndexRoute,
}

const EinsteinRouteWithChildren = EinsteinRoute._addFileChildren(
  EinsteinRouteChildren,
)

interface GridRouteChildren {
  GridJogarRoute: typeof GridJogarRoute
  GridIndexRoute: typeof GridIndexRoute
}

const GridRouteChildren: GridRouteChildren = {
  GridJogarRoute: GridJogarRoute,
  GridIndexRoute: GridIndexRoute,
}

const GridRouteWithChildren = GridRoute._addFileChildren(GridRouteChildren)

interface MatrizRouteChildren {
  MatrizJogarRoute: typeof MatrizJogarRoute
  MatrizIndexRoute: typeof MatrizIndexRoute
}

const MatrizRouteChildren: MatrizRouteChildren = {
  MatrizJogarRoute: MatrizJogarRoute,
  MatrizIndexRoute: MatrizIndexRoute,
}

const MatrizRouteWithChildren =
  MatrizRoute._addFileChildren(MatrizRouteChildren)

interface MemoriaRouteChildren {
  MemoriaJogarRoute: typeof MemoriaJogarRoute
  MemoriaResultadoRoute: typeof MemoriaResultadoRoute
  MemoriaIndexRoute: typeof MemoriaIndexRoute
}

const MemoriaRouteChildren: MemoriaRouteChildren = {
  MemoriaJogarRoute: MemoriaJogarRoute,
  MemoriaResultadoRoute: MemoriaResultadoRoute,
  MemoriaIndexRoute: MemoriaIndexRoute,
}

const MemoriaRouteWithChildren =
  MemoriaRoute._addFileChildren(MemoriaRouteChildren)

interface MorseRouteChildren {
  MorseMundo1Route: typeof MorseMundo1Route
  MorseIndexRoute: typeof MorseIndexRoute
}

const MorseRouteChildren: MorseRouteChildren = {
  MorseMundo1Route: MorseMundo1Route,
  MorseIndexRoute: MorseIndexRoute,
}

const MorseRouteWithChildren = MorseRoute._addFileChildren(MorseRouteChildren)

interface RecallRouteChildren {
  RecallJogarRoute: typeof RecallJogarRoute
  RecallResultadoRoute: typeof RecallResultadoRoute
  RecallIndexRoute: typeof RecallIndexRoute
}

const RecallRouteChildren: RecallRouteChildren = {
  RecallJogarRoute: RecallJogarRoute,
  RecallResultadoRoute: RecallResultadoRoute,
  RecallIndexRoute: RecallIndexRoute,
}

const RecallRouteWithChildren =
  RecallRoute._addFileChildren(RecallRouteChildren)

interface RegraRouteChildren {
  RegraJogarRoute: typeof RegraJogarRoute
  RegraIndexRoute: typeof RegraIndexRoute
}

const RegraRouteChildren: RegraRouteChildren = {
  RegraJogarRoute: RegraJogarRoute,
  RegraIndexRoute: RegraIndexRoute,
}

const RegraRouteWithChildren = RegraRoute._addFileChildren(RegraRouteChildren)

interface SequenciaRouteChildren {
  SequenciaJogarRoute: typeof SequenciaJogarRoute
  SequenciaIndexRoute: typeof SequenciaIndexRoute
}

const SequenciaRouteChildren: SequenciaRouteChildren = {
  SequenciaJogarRoute: SequenciaJogarRoute,
  SequenciaIndexRoute: SequenciaIndexRoute,
}

const SequenciaRouteWithChildren = SequenciaRoute._addFileChildren(
  SequenciaRouteChildren,
)

interface SlideRouteChildren {
  SlideJogarRoute: typeof SlideJogarRoute
  SlideIndexRoute: typeof SlideIndexRoute
}

const SlideRouteChildren: SlideRouteChildren = {
  SlideJogarRoute: SlideJogarRoute,
  SlideIndexRoute: SlideIndexRoute,
}

const SlideRouteWithChildren = SlideRoute._addFileChildren(SlideRouteChildren)

interface StroopRouteChildren {
  StroopJogarRoute: typeof StroopJogarRoute
  StroopIndexRoute: typeof StroopIndexRoute
}

const StroopRouteChildren: StroopRouteChildren = {
  StroopJogarRoute: StroopJogarRoute,
  StroopIndexRoute: StroopIndexRoute,
}

const StroopRouteWithChildren =
  StroopRoute._addFileChildren(StroopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AritRoute: AritRouteWithChildren,
  CalculoRoute: CalculoRouteWithChildren,
  CofresRoute: CofresRouteWithChildren,
  CriptoRoute: CriptoRouteWithChildren,
  CruzadaRoute: CruzadaRouteWithChildren,
  DicoticoRoute: DicoticoRouteWithChildren,
  EinsteinRoute: EinsteinRouteWithChildren,
  GridRoute: GridRouteWithChildren,
  MatrizRoute: MatrizRouteWithChildren,
  MemoriaRoute: MemoriaRouteWithChildren,
  MorseRoute: MorseRouteWithChildren,
  RecallRoute: RecallRouteWithChildren,
  RegraRoute: RegraRouteWithChildren,
  SequenciaRoute: SequenciaRouteWithChildren,
  SlideRoute: SlideRouteWithChildren,
  SobreRoute: SobreRoute,
  StroopRoute: StroopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
