/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StroopRouteImport } from './routes/stroop'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RegraRouteImport } from './routes/regra'
import { Route as MemoriaRouteImport } from './routes/memoria'
import { Route as GridRouteImport } from './routes/grid'
import { Route as CruzadaRouteImport } from './routes/cruzada'
import { Route as CalculoRouteImport } from './routes/calculo'
import { Route as AritRouteImport } from './routes/arit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StroopIndexRouteImport } from './routes/stroop.index'
import { Route as RegraIndexRouteImport } from './routes/regra.index'
import { Route as MemoriaIndexRouteImport } from './routes/memoria.index'
import { Route as GridIndexRouteImport } from './routes/grid.index'
import { Route as CruzadaIndexRouteImport } from './routes/cruzada.index'
import { Route as CalculoIndexRouteImport } from './routes/calculo.index'
import { Route as AritIndexRouteImport } from './routes/arit.index'
import { Route as StroopJogarRouteImport } from './routes/stroop.jogar'
import { Route as RegraJogarRouteImport } from './routes/regra.jogar'
import { Route as MemoriaResultadoRouteImport } from './routes/memoria.resultado'
import { Route as MemoriaJogarRouteImport } from './routes/memoria.jogar'
import { Route as GridJogarRouteImport } from './routes/grid.jogar'
import { Route as CruzadaJogarRouteImport } from './routes/cruzada.jogar'
import { Route as CalculoResultadoRouteImport } from './routes/calculo.resultado'
import { Route as CalculoJogarRouteImport } from './routes/calculo.jogar'
import { Route as AritJogarRouteImport } from './routes/arit.jogar'

const StroopRoute = StroopRouteImport.update({
  id: '/stroop',
  path: '/stroop',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RegraRoute = RegraRouteImport.update({
  id: '/regra',
  path: '/regra',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaRoute = MemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const CruzadaRoute = CruzadaRouteImport.update({
  id: '/cruzada',
  path: '/cruzada',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculoRoute = CalculoRouteImport.update({
  id: '/calculo',
  path: '/calculo',
  getParentRoute: () => rootRouteImport,
} as any)
const AritRoute = AritRouteImport.update({
  id: '/arit',
  path: '/arit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StroopIndexRoute = StroopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StroopRoute,
} as any)
const RegraIndexRoute = RegraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegraRoute,
} as any)
const MemoriaIndexRoute = MemoriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriaRoute,
} as any)
const GridIndexRoute = GridIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GridRoute,
} as any)
const CruzadaIndexRoute = CruzadaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CruzadaRoute,
} as any)
const CalculoIndexRoute = CalculoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalculoRoute,
} as any)
const AritIndexRoute = AritIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AritRoute,
} as any)
const StroopJogarRoute = StroopJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => StroopRoute,
} as any)
const RegraJogarRoute = RegraJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => RegraRoute,
} as any)
const MemoriaResultadoRoute = MemoriaResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => MemoriaRoute,
} as any)
const MemoriaJogarRoute = MemoriaJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => MemoriaRoute,
} as any)
const GridJogarRoute = GridJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => GridRoute,
} as any)
const CruzadaJogarRoute = CruzadaJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CruzadaRoute,
} as any)
const CalculoResultadoRoute = CalculoResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => CalculoRoute,
} as any)
const CalculoJogarRoute = CalculoJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => CalculoRoute,
} as any)
const AritJogarRoute = AritJogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => AritRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arit': typeof AritRouteWithChildren
  '/calculo': typeof CalculoRouteWithChildren
  '/cruzada': typeof CruzadaRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/memoria': typeof MemoriaRouteWithChildren
  '/regra': typeof RegraRouteWithChildren
  '/sobre': typeof SobreRoute
  '/stroop': typeof StroopRouteWithChildren
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit/': typeof AritIndexRoute
  '/calculo/': typeof CalculoIndexRoute
  '/cruzada/': typeof CruzadaIndexRoute
  '/grid/': typeof GridIndexRoute
  '/memoria/': typeof MemoriaIndexRoute
  '/regra/': typeof RegraIndexRoute
  '/stroop/': typeof StroopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit': typeof AritIndexRoute
  '/calculo': typeof CalculoIndexRoute
  '/cruzada': typeof CruzadaIndexRoute
  '/grid': typeof GridIndexRoute
  '/memoria': typeof MemoriaIndexRoute
  '/regra': typeof RegraIndexRoute
  '/stroop': typeof StroopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arit': typeof AritRouteWithChildren
  '/calculo': typeof CalculoRouteWithChildren
  '/cruzada': typeof CruzadaRouteWithChildren
  '/grid': typeof GridRouteWithChildren
  '/memoria': typeof MemoriaRouteWithChildren
  '/regra': typeof RegraRouteWithChildren
  '/sobre': typeof SobreRoute
  '/stroop': typeof StroopRouteWithChildren
  '/arit/jogar': typeof AritJogarRoute
  '/calculo/jogar': typeof CalculoJogarRoute
  '/calculo/resultado': typeof CalculoResultadoRoute
  '/cruzada/jogar': typeof CruzadaJogarRoute
  '/grid/jogar': typeof GridJogarRoute
  '/memoria/jogar': typeof MemoriaJogarRoute
  '/memoria/resultado': typeof MemoriaResultadoRoute
  '/regra/jogar': typeof RegraJogarRoute
  '/stroop/jogar': typeof StroopJogarRoute
  '/arit/': typeof AritIndexRoute
  '/calculo/': typeof CalculoIndexRoute
  '/cruzada/': typeof CruzadaIndexRoute
  '/grid/': typeof GridIndexRoute
  '/memoria/': typeof MemoriaIndexRoute
  '/regra/': typeof RegraIndexRoute
  '/stroop/': typeof StroopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arit'
    | '/calculo'
    | '/cruzada'
    | '/grid'
    | '/memoria'
    | '/regra'
    | '/sobre'
    | '/stroop'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cruzada/jogar'
    | '/grid/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/regra/jogar'
    | '/stroop/jogar'
    | '/arit/'
    | '/calculo/'
    | '/cruzada/'
    | '/grid/'
    | '/memoria/'
    | '/regra/'
    | '/stroop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sobre'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cruzada/jogar'
    | '/grid/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/regra/jogar'
    | '/stroop/jogar'
    | '/arit'
    | '/calculo'
    | '/cruzada'
    | '/grid'
    | '/memoria'
    | '/regra'
    | '/stroop'
  id:
    | '__root__'
    | '/'
    | '/arit'
    | '/calculo'
    | '/cruzada'
    | '/grid'
    | '/memoria'
    | '/regra'
    | '/sobre'
    | '/stroop'
    | '/arit/jogar'
    | '/calculo/jogar'
    | '/calculo/resultado'
    | '/cruzada/jogar'
    | '/grid/jogar'
    | '/memoria/jogar'
    | '/memoria/resultado'
    | '/regra/jogar'
    | '/stroop/jogar'
    | '/arit/'
    | '/calculo/'
    | '/cruzada/'
    | '/grid/'
    | '/memoria/'
    | '/regra/'
    | '/stroop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AritRoute: typeof AritRouteWithChildren
  CalculoRoute: typeof CalculoRouteWithChildren
  CruzadaRoute: typeof CruzadaRouteWithChildren
  GridRoute: typeof GridRouteWithChildren
  MemoriaRoute: typeof MemoriaRouteWithChildren
  RegraRoute: typeof RegraRouteWithChildren
  SobreRoute: typeof SobreRoute
  StroopRoute: typeof StroopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stroop': {
      id: '/stroop'
      path: '/stroop'
      fullPath: '/stroop'
      preLoaderRoute: typeof StroopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regra': {
      id: '/regra'
      path: '/regra'
      fullPath: '/regra'
      preLoaderRoute: typeof RegraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria': {
      id: '/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof MemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruzada': {
      id: '/cruzada'
      path: '/cruzada'
      fullPath: '/cruzada'
      preLoaderRoute: typeof CruzadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculo': {
      id: '/calculo'
      path: '/calculo'
      fullPath: '/calculo'
      preLoaderRoute: typeof CalculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arit': {
      id: '/arit'
      path: '/arit'
      fullPath: '/arit'
      preLoaderRoute: typeof AritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroop/': {
      id: '/stroop/'
      path: '/'
      fullPath: '/stroop/'
      preLoaderRoute: typeof StroopIndexRouteImport
      parentRoute: typeof StroopRoute
    }
    '/regra/': {
      id: '/regra/'
      path: '/'
      fullPath: '/regra/'
      preLoaderRoute: typeof RegraIndexRouteImport
      parentRoute: typeof RegraRoute
    }
    '/memoria/': {
      id: '/memoria/'
      path: '/'
      fullPath: '/memoria/'
      preLoaderRoute: typeof MemoriaIndexRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/grid/': {
      id: '/grid/'
      path: '/'
      fullPath: '/grid/'
      preLoaderRoute: typeof GridIndexRouteImport
      parentRoute: typeof GridRoute
    }
    '/cruzada/': {
      id: '/cruzada/'
      path: '/'
      fullPath: '/cruzada/'
      preLoaderRoute: typeof CruzadaIndexRouteImport
      parentRoute: typeof CruzadaRoute
    }
    '/calculo/': {
      id: '/calculo/'
      path: '/'
      fullPath: '/calculo/'
      preLoaderRoute: typeof CalculoIndexRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/arit/': {
      id: '/arit/'
      path: '/'
      fullPath: '/arit/'
      preLoaderRoute: typeof AritIndexRouteImport
      parentRoute: typeof AritRoute
    }
    '/stroop/jogar': {
      id: '/stroop/jogar'
      path: '/jogar'
      fullPath: '/stroop/jogar'
      preLoaderRoute: typeof StroopJogarRouteImport
      parentRoute: typeof StroopRoute
    }
    '/regra/jogar': {
      id: '/regra/jogar'
      path: '/jogar'
      fullPath: '/regra/jogar'
      preLoaderRoute: typeof RegraJogarRouteImport
      parentRoute: typeof RegraRoute
    }
    '/memoria/resultado': {
      id: '/memoria/resultado'
      path: '/resultado'
      fullPath: '/memoria/resultado'
      preLoaderRoute: typeof MemoriaResultadoRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/memoria/jogar': {
      id: '/memoria/jogar'
      path: '/jogar'
      fullPath: '/memoria/jogar'
      preLoaderRoute: typeof MemoriaJogarRouteImport
      parentRoute: typeof MemoriaRoute
    }
    '/grid/jogar': {
      id: '/grid/jogar'
      path: '/jogar'
      fullPath: '/grid/jogar'
      preLoaderRoute: typeof GridJogarRouteImport
      parentRoute: typeof GridRoute
    }
    '/cruzada/jogar': {
      id: '/cruzada/jogar'
      path: '/jogar'
      fullPath: '/cruzada/jogar'
      preLoaderRoute: typeof CruzadaJogarRouteImport
      parentRoute: typeof CruzadaRoute
    }
    '/calculo/resultado': {
      id: '/calculo/resultado'
      path: '/resultado'
      fullPath: '/calculo/resultado'
      preLoaderRoute: typeof CalculoResultadoRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/calculo/jogar': {
      id: '/calculo/jogar'
      path: '/jogar'
      fullPath: '/calculo/jogar'
      preLoaderRoute: typeof CalculoJogarRouteImport
      parentRoute: typeof CalculoRoute
    }
    '/arit/jogar': {
      id: '/arit/jogar'
      path: '/jogar'
      fullPath: '/arit/jogar'
      preLoaderRoute: typeof AritJogarRouteImport
      parentRoute: typeof AritRoute
    }
  }
}

interface AritRouteChildren {
  AritJogarRoute: typeof AritJogarRoute
  AritIndexRoute: typeof AritIndexRoute
}

const AritRouteChildren: AritRouteChildren = {
  AritJogarRoute: AritJogarRoute,
  AritIndexRoute: AritIndexRoute,
}

const AritRouteWithChildren = AritRoute._addFileChildren(AritRouteChildren)

interface CalculoRouteChildren {
  CalculoJogarRoute: typeof CalculoJogarRoute
  CalculoResultadoRoute: typeof CalculoResultadoRoute
  CalculoIndexRoute: typeof CalculoIndexRoute
}

const CalculoRouteChildren: CalculoRouteChildren = {
  CalculoJogarRoute: CalculoJogarRoute,
  CalculoResultadoRoute: CalculoResultadoRoute,
  CalculoIndexRoute: CalculoIndexRoute,
}

const CalculoRouteWithChildren =
  CalculoRoute._addFileChildren(CalculoRouteChildren)

interface CruzadaRouteChildren {
  CruzadaJogarRoute: typeof CruzadaJogarRoute
  CruzadaIndexRoute: typeof CruzadaIndexRoute
}

const CruzadaRouteChildren: CruzadaRouteChildren = {
  CruzadaJogarRoute: CruzadaJogarRoute,
  CruzadaIndexRoute: CruzadaIndexRoute,
}

const CruzadaRouteWithChildren =
  CruzadaRoute._addFileChildren(CruzadaRouteChildren)

interface GridRouteChildren {
  GridJogarRoute: typeof GridJogarRoute
  GridIndexRoute: typeof GridIndexRoute
}

const GridRouteChildren: GridRouteChildren = {
  GridJogarRoute: GridJogarRoute,
  GridIndexRoute: GridIndexRoute,
}

const GridRouteWithChildren = GridRoute._addFileChildren(GridRouteChildren)

interface MemoriaRouteChildren {
  MemoriaJogarRoute: typeof MemoriaJogarRoute
  MemoriaResultadoRoute: typeof MemoriaResultadoRoute
  MemoriaIndexRoute: typeof MemoriaIndexRoute
}

const MemoriaRouteChildren: MemoriaRouteChildren = {
  MemoriaJogarRoute: MemoriaJogarRoute,
  MemoriaResultadoRoute: MemoriaResultadoRoute,
  MemoriaIndexRoute: MemoriaIndexRoute,
}

const MemoriaRouteWithChildren =
  MemoriaRoute._addFileChildren(MemoriaRouteChildren)

interface RegraRouteChildren {
  RegraJogarRoute: typeof RegraJogarRoute
  RegraIndexRoute: typeof RegraIndexRoute
}

const RegraRouteChildren: RegraRouteChildren = {
  RegraJogarRoute: RegraJogarRoute,
  RegraIndexRoute: RegraIndexRoute,
}

const RegraRouteWithChildren = RegraRoute._addFileChildren(RegraRouteChildren)

interface StroopRouteChildren {
  StroopJogarRoute: typeof StroopJogarRoute
  StroopIndexRoute: typeof StroopIndexRoute
}

const StroopRouteChildren: StroopRouteChildren = {
  StroopJogarRoute: StroopJogarRoute,
  StroopIndexRoute: StroopIndexRoute,
}

const StroopRouteWithChildren =
  StroopRoute._addFileChildren(StroopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AritRoute: AritRouteWithChildren,
  CalculoRoute: CalculoRouteWithChildren,
  CruzadaRoute: CruzadaRouteWithChildren,
  GridRoute: GridRouteWithChildren,
  MemoriaRoute: MemoriaRouteWithChildren,
  RegraRoute: RegraRouteWithChildren,
  SobreRoute: SobreRoute,
  StroopRoute: StroopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
